---
# tasks file for nginx
- name: Install nginx
  become: true
  apt:
    name: nginx
    state: present

- name: Ensure nginx is started and enabled
  become: true
  service:
    name: nginx
    state: started
    enabled: true

- name: install PHP
  apt:
    name:
      - php
      - php-mysqlnd
      - php-gd
      - php-curl
    state: present
