pipeline {
  agent any

  environment {
    ANSIBLE_CONFIG = '$WORKSPACE/deploy/ansible.cfg'
  }

  parameters {
    string name: 'env', defaultValue: 'dev', description: 'This is the inventory file for the environment to deploy configuration'
  }

  stages {
    stage ('Initial cleanup') {
      steps {
        dir('$WORKSPACE') {
          echo "${WORKSPACE}"
          deleteDir()
        }
      }
    }

    stage ('Checkout SCM') {
      steps {
        git branch: '$BRANCH_NAME', url: 'https://github.com/toritsejuFO/ansible-config-mgt-project-14.git'
      }
    }

    stage ('Set roles in ansible dynamically') {
      steps {
        sh 'sed -i "3 a roles_path=${WORKSPACE}/roles" ${ANSIBLE_CONFIG}'
      }
    }

    stage ('Run ansible playbook') {
      steps {
        ansiblePlaybook become: true, colorized: true, credentialsId: 'private-key', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/${env}.txt', playbook: 'playbook/site.yml'
      }
    }

    stage ('Clean up') {
      steps {
        cleanWs()
      }
    }
  }
}
