pipeline {
  agent any

  stages {
    stage ('Initial cleanup') {
      steps {
        dir('$WORKSPACE') {
          echo '$WORKSPACE'
          deleteDir();
        }
      }
    }

    stage('Build') {
      steps {
        script {
          sh 'echo "Building stage"'
        }
      }
    }

    stage('Test') {
      steps {
        script {
          sh 'echo "Testing stage"'
        }
      }
    }

    stage('Package') {
      steps {
        script {
          sh 'echo "Packageing stage"'
        }
      }
    }

    stage('Deploy') {
      steps {
        script {
          sh 'echo "Deploying stage"'
        }
      }
    }

    stage('Clean up') {
      steps {
        cleanWs notFailBuild: true
      }
    }
  }
}
