---
# tasks file for artifactory

- name: install java 11 and auxiliary packages
  yum:
    name:
      - java-11-openjdk-devel
      - wget
      - unzip
    state: present

- name: Configuring java path
  template:
    src: templates/bash-profile.j2
    dest: .bash_profile

- name: reload bash profile
  shell: source ~/.bash_profile

- name: add the repository key to repos list
  get_url:
    url: https://releases.jfrog.io/artifactory/artifactory-rpms/artifactory-rpms.repo
    dest: /etc/yum.repos.d/jfrog-artifactory-rpms.repo
    mode: "0755"

- name: update cache
  yum:
    update_cache: yes

- name: install artifactory
  yum:
    name: jfrog-artifactory-oss
    state: present

- name: start and enable artifactory
  service:
    name: artifactory
    state: started
    enabled: yes
